services:
  - type: web
    name: english-hub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
