# Generated by Django 6.0.2 on 2026-02-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clubpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpage',
            name='president_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
