# Generated by Django 6.0.2 on 2026-02-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_clubpage_president_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_info', models.CharField(help_text='e.g., March 15 or Every Friday', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, help_text='Optional link to a page or registration form')),
            ],
        ),
    ]
