# Generated by Django 6.0.2 on 2026-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_info',
            field=models.CharField(help_text='e.g., Every Wednesday  or Every Friday', max_length=100),
        ),
    ]
